added ts config
saiumesh535/js-validation pull request #2
Opened 2018-07-12 13:22 UTC by saiumesh535

1. added ts config and written files in TS.

2018-07-12 13:44 UTC, lava-dukanam requested changes
added some minor comments

2018-07-12 13:44 UTC, lava-dukanam commented on validation.js
> +var validator = {
why was this changed from const to var?

2018-07-12 13:44 UTC, lava-dukanam commented on validation.js
> +var typedValidations = {
why was this changed from const to var?

2018-07-12 13:44 UTC, lava-dukanam commented on validation.js
> +    var validation = Object.keys(config[key]).reduce(function (cumm, value) {
why was this changed from const to var?
can we switch to fat arrow syntax?

2018-07-12 13:49 UTC, saiumesh535 commented on validation.js
> +var validator = {
compiled file. we will use webpack to do this as discussed.

2018-07-16 13:03 UTC, saiumesh535 commented
closed, we will implement later.

2018-07-16 13:03 UTC, closed without merging